name: Build, test, lint and release JiraLint
on: [push]
jobs:
  build_and_test_and_release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Dependencies
        # Skip post-install scripts here, as a malicious script could steal env vars
        run: npm ci --ignore-scripts
      # Make sure the code base can be built.
      - name: build Artifact
        run: npm run build
      - name: Run Unit Test
        run: npm run test
      - name: Run Coverage
        run: npm run coverage
      - name: Run Lint
        run: npm run lint
      - name: Run Semantic Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}